command:
  - streamlit
  - run
  - app.py
  - --server.enableCORS
  - "false"
  - --server.enableXsrfProtection
  - "false"

env:
  - name: ENDPOINT_NAME
    value: 'projects/ticketing-system/branches/production/endpoints/primary'

    